"""
Process data on ArcGIS license usage in report from OpenLM and write to Excel file sheets per and for Power BI Team.

"""


def main():

    import pandas as pd

    data_file = r"Example Activity Report Generated by OpenLM.csv"
    output_file = r"TEST.xlsx"
    fields_of_interest = ["Feature", "Product", "Start Time", "End Time", "Workstation", "User Name", "First Name",
                          "Last Name", "Email", "Total usage time (hours)", "Usage Time w/in filter period",
                          "Token Usage Time w/in filter period"]
    excel_date_format = "YYYY-MM-DD"
    excel_datetime_format = "YYYY-MM-DD HH:MM:SS"


    # Create master dataframe from report csv file
    master_df = pd.read_csv(data_file)
    # print(master_df.head())
    # print(master_df.info())

    # Slim the dataframe size by isolating fields of interest for output
    master_df_slim = master_df[fields_of_interest]
    master_df_slim.info()


    # with pd.ExcelWriter(path=output_file, date_format=excel_date_format, datetime_format=excel_datetime_format) as writer:
    #     pass


if __name__ == "__main__":
    main()
