"""
Process data on ArcGIS license usage in report from OpenLM and write to Excel file sheets per and for Power BI Team.

"""


def main():

    import pandas as pd
    import numpy as np

    data_file = r"Example Activity Report Generated by OpenLM.csv"
    output_file = r"TEST.xlsx"
    fields_of_interest = ["Feature", "Product", "Start Time", "End Time", "Workstation", "User Name", "First Name",
                          "Last Name", "Email", "Total usage time (hours)", "Usage Time w/in filter period",
                          "Token Usage Time w/in filter period"]
    new_fields = ["Agency", "Date", "Product_Workstation", "Product_Username"]
    excel_date_format = "YYYY-MM-DD"
    excel_datetime_format = "YYYY-MM-DD HH:MM:SS"

    # Create master dataframe from report csv file
    master_df = pd.read_csv(data_file)

    # Add the new fields to the master dataframe
    generic_series = pd.Series(data=np.NaN, index=master_df.index)
    for field in new_fields:
        master_df[field] = generic_series

    # Calculate Product_Workstation field
    master_df["Product_Workstation"] = master_df["Product"] + master_df["Workstation"]
    # Calculate Product_Username field
    # Calculate Date field
    # Calculate Agency field

    # Create the whole list of fields of interest for analysis only. Slimming dataframe to exclude unnecessary fields
    fields_of_interest.extend(new_fields)
    master_df_slim = master_df[fields_of_interest]

    # Sanity checks
    print(master_df_slim.info())
    print(master_df_slim.head())
    print(master_df_slim["Product_Workstation"])



    # Write output datasets to excel file sheets
    # with pd.ExcelWriter(path=output_file, date_format=excel_date_format, datetime_format=excel_datetime_format) as writer:
    #     pass


if __name__ == "__main__":
    main()
